#!/bin/bash
if [ $(id -u) != "0" ]; then
    echo "This install script must be run as root" 1>&2
    exit 1
fi


mkdir -p /usr/share/spgit
rm -rf /usr/share/spgit/*

cp spgit /usr/share/spgit/
cp mac* /usr/share/spgit/
ln -sf /usr/share/spgit/spgit /usr/bin

echo INSTALLED!
