#!/bin/sh
git add -A
dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify \
/org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get \
string:'org.mpris.MediaPlayer2.Player' string:'Metadata' | awk '
/:artist/{a=1;next}
/:title/{t=1;next}
/:url/{u=1;next}
a && /string/{
  sub(/^.*string /,"")
  artist=$0
  gsub("\"","",artist)
  a=0; next
}
t && /string/{
  sub(/^.*string /,"")
  title=$0
  gsub("\"","",title)
  t=0;next
}
u && /string/{
  sub(/^.*string /,"")
  url=$0
  gsub("\"","",url)
  u=0;next
}
END{
  printf("\"♫ %s - %s♫ %si\"\n", title, artist, url)
}' - | git commit -m -
